# Generated by Django 5.2.3 on 2025-07-08 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Loyiha nomi')),
                ('description', models.TextField(verbose_name='Loyiha tavsifi')),
                ('base_hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Standart soatbay stavka')),
                ('status', models.CharField(choices=[('ACTIVE', 'Faol'), ('CLOSED', 'Yopilgan')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Loyiha (Job)',
                'verbose_name_plural': 'Loyihalar (Jobs)',
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Vakansiya sarlavhasi')),
                ('description', models.TextField(verbose_name='Vakansiya tavsifi')),
                ('requirements', models.TextField(verbose_name='Talablar')),
                ('slots_available', models.PositiveIntegerField(default=1, verbose_name="Bo'sh o'rinlar soni")),
                ('application_deadline', models.DateField(verbose_name='Ariza topshirishning oxirgi kuni')),
                ('status', models.CharField(choices=[('OPEN', 'Ochiq'), ('CLOSED', 'Yopilgan')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_vacancies', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Vakansiya',
                'verbose_name_plural': 'Vakansiyalar',
                'db_table': 'job_vacancies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('REVIEWING', "Ko'rib chiqilmoqda"), ('ACCEPTED', 'Qabul qilingan'), ('REJECTED', 'Rad etilgan')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Staff uchun izohlar')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_applications', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobvacancy')),
            ],
            options={
                'db_table': 'vacancy_applications',
                'ordering': ['-applied_at'],
                'unique_together': {('vacancy', 'applicant')},
            },
        ),
    ]
