# Generated by Django 5.2.3 on 2025-07-02 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='workspace',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_vacancies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='vacancyapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacancyapplication',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobvacancy'),
        ),
        migrations.AlterUniqueTogether(
            name='vacancyapplication',
            unique_together={('vacancy', 'applicant')},
        ),
    ]
