# Generated by Django 5.2.3 on 2025-06-23 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ish Maydoni')),
                ('description', models.TextField(blank=True, verbose_name='Tavsifi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol ish maydoni')),
                ('max_members', models.PositiveIntegerField(default=50, verbose_name="Maksimal a'zolar soni")),
                ('workspace_type', models.CharField(choices=[('GENERAL', 'General'), ('PROJECT', 'Project'), ('STUDY', 'Study'), ('MEETING', 'Meeting')], default='GENERAL', max_length=20, verbose_name='Ish maydoni turi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_workspaces', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Ish Maydoni',
                'verbose_name_plural': 'Ish Maydonlari',
                'db_table': 'workspaces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('TEAMLEADER', 'Team Leader'), ('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('RECRUITER', 'Recruiter')], max_length=20, verbose_name="A'zolik roli")),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name="Faol a'zo")),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name="So'nggi faoliyat")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workspaces.workspace', verbose_name='Ish maydoni')),
            ],
            options={
                'verbose_name': "Ish Maydoni A'zosi",
                'verbose_name_plural': "Ish Maydoni A'zolari",
                'db_table': 'workspace_members',
                'ordering': ['-joined_at'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'user'), name='unique_workspace_membership')],
            },
        ),
    ]
