# Generated by Django 5.2.3 on 2025-07-02 19:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Hisobot sanasi')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Ishlangan soat')),
                ('work_description', models.TextField(verbose_name='Bajarilgan ish tavsifi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kunlik Hisobot',
                'verbose_name_plural': 'Kunlik Hisobotlar',
                'db_table': 'daily_reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('file', models.FileField(upload_to='monthly_reports/%Y/%m/')),
                ('status', models.CharField(choices=[('GENERATED', 'Yaratilgan'), ('APPROVED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan')], default='GENERATED', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Oylik Hisobot',
                'verbose_name_plural': 'Oylik Hisobotlar',
                'db_table': 'monthly_reports',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Oy')),
                ('year', models.IntegerField(verbose_name='Yil')),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Jami soat')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Soatbay stavka')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umumiy summa (barcha summa)')),
                ('deduction_percentage', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='Ushlanma foizi (%)')),
                ('deduction_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ushlanma miqdori')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Sof miqdor (qo'lga tegadigan)")),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('APPROVED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan'), ('PAID', "To'langan")], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Oylik Maosh Yozuvi',
                'verbose_name_plural': 'Oylik Maosh Yozuvlari',
                'db_table': 'salary_records',
                'ordering': ['-year', '-month'],
            },
        ),
    ]
