# Generated by Django 5.2.3 on 2025-07-02 19:04

import apps.reports.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL, validators=[apps.reports.models.validate_student_user]),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_reports', to=settings.AUTH_USER_MODEL, validators=[apps.reports.models.validate_staff_user]),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to=settings.AUTH_USER_MODEL, validators=[apps.reports.models.validate_student_user]),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_salaries', to=settings.AUTH_USER_MODEL, validators=[apps.reports.models.validate_staff_user]),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to=settings.AUTH_USER_MODEL, validators=[apps.reports.models.validate_student_user]),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='salary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_report', to='reports.salaryrecord'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('student', 'report_date', 'workspace')},
        ),
        migrations.AlterUniqueTogether(
            name='salaryrecord',
            unique_together={('student', 'workspace', 'year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlyreport',
            unique_together={('student', 'workspace', 'year', 'month')},
        ),
    ]
