# Generated by Django 5.2.3 on 2025-07-08 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Rejalashtirilgan'), ('ONGOING', 'Davom etmoqda'), ('COMPLETED', 'Tugallangan'), ('CANCELLED', 'Bekor qilingan')], default='SCHEDULED', max_length=20)),
                ('meeting_link', models.URLField(blank=True, max_length=512, null=True)),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('audience_type', models.CharField(choices=[('WORKSPACE_MEMBERS', "Ish maydoni a'zolari"), ('ALL_STAFF', 'Barcha xodimlar'), ('SPECIFIC_USERS', 'Tanlangan foydalanuvchilar')], default='WORKSPACE_MEMBERS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_meetings', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'meetings',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INVITED', 'Taklif qilingan'), ('ACCEPTED', 'Qabul qilingan'), ('DECLINED', 'Rad etilgan')], default='INVITED', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting_attendees',
                'ordering': ['user__first_name'],
                'unique_together': {('meeting', 'user')},
            },
        ),
    ]
